const data ={
    products:[
        {
            name: 'The LaGaurdia Two-piece',
            slug: 'free-shirt',
            category: 'Two-piece',
            image: '/images/andrea_iyamah.png',
            price: 70,
            brand: 'Andrea Iyamah',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A popular Two-piece',
            isFeatured: true,
            banner: '/images/andrea_iyamah.jpg',
        },
        {
          name: 'Atafo suit Pants',
          slug: 'atafo-suit-pants',
          category: 'Pants',
          image: '/images/mai_atafo.jpeg',
          price: 90,
          brand: 'Mai Atafo',
          rating: 2.9,
          numReviews: 13,
          countInStock: 20,
          description: 'Smart looking pants',
        },
        {
          name: 'Ugo Two-piece',
          slug: 'ugo-two-piece',
          category: 'Two-piece',
          image: '/images/ugo_monye.jpeg',
          price: 95,
          brand: 'Ugo Monye',
          rating: 3.5,
          numReviews: 7,
          countInStock: 20,
          description: 'A super popular Two-piece',
        },
        {
          name: 'The Rendoll Party-Popper',
          slug: 'rendoll-party-popper',
          category: 'Dress',
          image: '/images/rendoll.jpeg',
          price: 80,
          brand: 'Rendoll',
          rating: 3.2,
          numReviews: 10,
          countInStock: 20,
          description: 'A popular Outfit',
          isFeatured: true,
          banner: '/images/rendoll.jpg',
        },
        {
          name: 'Kai Stylish Dress',
          slug: 'kai-stylish-dress',
          category: 'Dress',
          image: '/images/kai_collective.jpeg',
          price: 90,
          brand: 'Kai Kollective',
          rating: 4.5,
          numReviews: 3,
          countInStock: 20,
          description: 'A popular Dress',
        },
        {
          name: 'The David Classic shirt',
          slug: 'david-classic-shirt',
          category: 'Shirt',
          image: '/images/david_wej.jpeg',
          price: 75,
          brand: 'David Wej',
          rating: 2.4,
          numReviews: 14,
          countInStock: 20,
          description: 'A popular Shirt',
        },

    ]
}

export default data;